name: budget_app
description: A Flutter project to try MVVM and Riverpod Hooks.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter_hooks: ^0.18.0
  flutter_svg: 1.1.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.3
  hooks_riverpod: ^2.0.0-dev.7
  logger: ^1.1.0
  sign_button: ^2.0.2
  url_strategy: ^0.2.0
  url_launcher: 6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
